export function isWindows(): boolean;
export function isWindowsX86(): boolean;
export function isWindowsX64(): boolean;
export function isWin11orGreater(): boolean;
export function isWin10orGreater(): boolean;
export function isWin8orGreater(): boolean;
export function isWin7orGreater(): boolean;
export function isWin11orLesser(): boolean;
export function isWin10orLesser(): boolean;
export function isWin8orLesser(): boolean;
export function isWin7orLesser(): boolean;
export function isWin11(): boolean;
export function isWin10(): boolean;
export function isWin8(): boolean;
export function isWin7(): boolean;
export { isWindowsX86 as isWin32, isWindowsX64 as isWin64 };
