export function isArray(value: unknown): boolean;
export function isArrayNotEmpty(value: unknown): boolean;
export function isArrayOfString(value: unknown): boolean;
export function isSizeArrayOfString(value: unknown, length: number): boolean;
export function isArrayOfStringNotEmpty(value: unknown): boolean;
export function isSizeArrayOfStringNotEmpty(value: unknown, length: number): boolean;
export function isArrayOfStringLike(value: unknown, pattern: RegExp | string): boolean;
export function isSizeArrayOfStringLike(value: unknown, length: number, pattern: RegExp | string): boolean;
export function isArrayOfNumber(value: unknown): boolean;
export function isSizeArrayOfNumber(value: unknown, length: number): boolean;
export function isArrayOfNumberWithinRange(value: unknown, min: number, max: number): boolean;
export function isSizeArrayOfNumberWithinRange(value: unknown, length: number, min: number, max: number): boolean;
export function isArrayOfInteger(value: unknown): boolean;
export function isSizeArrayOfInteger(value: unknown, length: number): boolean;
export function isArrayOfIntegerPositive(value: unknown): boolean;
export function isSizeArrayOfIntegerPositive(value: unknown, length: number): boolean;
export function isArrayOfIntegerPositiveOrZero(value: unknown): boolean;
export function isSizeArrayOfIntegerPositiveOrZero(value: unknown, length: number): boolean;
export function isArrayOfIntegerWithinRange(value: unknown, min: number, max: number): boolean;
export function isSizeArrayOfIntegerWithinRange(value: unknown, length: number, min: number, max: number): boolean;
export function isArrayOfObj(value: unknown): boolean;
export function isSizeArrayOfObj(value: unknown, length: number): boolean;
export function isArrayOfObjWithProperties(value: unknown, prop: string[]): boolean;
export function isSizeArrayOfObjWithProperties(value: unknown, length: number, prop: string[]): boolean;
export function isArrayOfObjLike(value: unknown, schema: object): boolean;
export function isArrayOfSomeObjLike(value: unknown, schema: object): boolean;
export function isSizeArrayOfObjLike(value: unknown, length: number, schema: object): boolean;
export function isArrayOfUint8Array(value: unknown): boolean;
export function isSizeArrayOfUint8Array(value: unknown, length: number): boolean;
export function isArrayOfBuffer(value: unknown): boolean; //alias (backward compatibility)
export function isSizeArrayOfBuffer(value: unknown, length: number): boolean; //alias (backward compatibility)
