export function shouldArray(value: unknown, error?: Error | string | null): void;
export function shouldArrayNotEmpty(value: unknown, error?: Error | string | null): void;
export function shouldArrayOfString(value: unknown, error?: Error | string | null): void;
export function shouldSizeArrayOfString(value: unknown, length: number, error?: Error | string | null): void;
export function shouldArrayOfStringNotEmpty(value: unknown, error?: Error | string | null): void;
export function shouldSizeArrayOfStringNotEmpty(value: unknown, length: number, error?: Error | string | null): void;
export function shouldArrayOfStringLike(value: unknown, pattern: RegExp, error?: Error | string | null): void;
export function shouldSizeArrayOfStringLike(value: unknown, length: number, pattern: RegExp, error?: Error | string | null): void;
export function shouldArrayOfNumber(value: unknown, error?: Error | string | null): void;
export function shouldSizeArrayOfNumber(value: unknown, length: number, error?: Error | string | null): void;
export function shouldArrayOfNumberWithinRange(value: unknown, min: number, max: number, error?: Error | string | null): void;
export function shouldSizeArrayOfNumberWithinRange(value: unknown, length: number, min: number, max: number, error?: Error | string | null): void;
export function shouldArrayOfInteger(value: unknown, error?: Error | string | null): void;
export function shouldSizeArrayOfInteger(value: unknown, length: number, error?: Error | string | null): void;
export function shouldArrayOfIntegerPositive(value: unknown, error?: Error | string | null): void;
export function shouldSizeArrayOfIntegerPositive(value: unknown, length: number, error?: Error | string | null): void;
export function shouldArrayOfIntegerPositiveOrZero(value: unknown, error?: Error | string | null): void;
export function shouldSizeArrayOfIntegerPositiveOrZero(value: unknown, length: number, error?: Error | string | null): void;
export function shouldArrayOfIntegerWithinRange(value: unknown, min: number, max: number, error?: Error | string | null): void;
export function shouldSizeArrayOfIntegerWithinRange(value: unknown, length: number, min: number, max: number, error?: Error | string | null): void;
export function shouldArrayOfObj(value: unknown, error?: Error | string | null): void;
export function shouldSizeArrayOfObj(value: unknown, length: number, error?: Error | string | null): void;
export function shouldArrayOfObjWithProperties(value: unknown, prop: string[], error?: Error | string | null): void;
export function shouldSizeArrayOfObjWithProperties(value: unknown, length: number, prop: string[], error?: Error | string | null): void;
export function shouldArrayOfObjLike(value: unknown, schema: object, error?: Error | string | null): void;
export function shouldArrayOfSomeObjLike(value: unknown, schema: object, error?: Error | string | null): void;
export function shouldSizeArrayOfObjLike(value: unknown, length: number, schema: object, error?: Error | string | null): void;
export function shouldArrayOfUint8Array(value: unknown, error?: Error | string | null): void;
export function shouldSizeArrayOfUint8Array(value: unknown, length: number, error?: Error | string | null): void;
export function shouldArrayOfBuffer(value: unknown, error?: Error | string | null): void; //alias (backward compatibility)
export function shouldSizeArrayOfBuffer(value: unknown, length: number, error?: Error | string | null): void; //alias (backward compatibility)
