export function asArray(value: unknown): [] | null;
export function asArrayNotEmpty(value: unknown): [] | null;
export function asArrayOfString(value: unknown): string[] | null;
export function asSizeArrayOfString(value: unknown, length: number): string[] | null;
export function asArrayOfStringNotEmpty(value: unknown): string[] | null;
export function asSizeArrayOfStringNotEmpty(value: unknown, length: number): string[] | null;
export function asArrayOfStringLike(value: unknown, pattern: RegExp): string[] | null;
export function asSizeArrayOfStringLike(value: unknown, length: number, pattern: RegExp): string[] | null;
export function asArrayOfNumber(value: unknown): number[] | null;
export function asSizeArrayOfNumber(value: unknown, length: number): number[] | null;
export function asArrayOfNumberWithinRange(value: unknown, min: number, max: number): number[] | null;
export function asSizeArrayOfNumberWithinRange(value: unknown, length: number, min: number, max: number): number[] | null;
export function asArrayOfInteger(value: unknown): number[] | null;
export function asSizeArrayOfInteger(value: unknown, length: number): number[] | null;
export function asArrayOfIntegerPositive(value: unknown): number[] | null;
export function asSizeArrayOfIntegerPositive(value: unknown, length: number): number[] | null;
export function asArrayOfIntegerPositiveOrZero(value: unknown): number[] | null;
export function asSizeArrayOfIntegerPositiveOrZero(value: unknown, length: number): number[] | null;
export function asArrayOfIntegerWithinRange(value: unknown, min: number, max: number): number[] | null;
export function asSizeArrayOfIntegerWithinRange(value: unknown, length: number, min: number, max: number): number[] | null;
export function asArrayOfObj(value: unknown): object[] | null;
export function asSizeArrayOfObj(value: unknown, length: number): object[] | null;
export function asArrayOfObjWithProperties(value: unknown, prop: string[]): object[] | null;
export function asSizeArrayOfObjWithProperties(value: unknown, length: number, prop: string[]): object[] | null;
export function asArrayOfObjLike(value: unknown, schema: object): object[] | null;
export function asArrayOfSomeObjLike(value: unknown, schema: object): object[] | null;
export function asSizeArrayOfObjLike(value: unknown, length: number, schema: object): object[] | null;
export function asArrayOfUint8Array(value: unknown): Uint8Array[] | Buffer[] | null;
export function asSizeArrayOfUint8Array(value: unknown, length: number): Uint8Array[] | Buffer[] | null;
export function asArrayOfBuffer(value: unknown): Uint8Array[] | Buffer[] | null; //alias (backward compatibility)
export function asSizeArrayOfBuffer(value: unknown, length: number): Uint8Array[] | Buffer[] | null; //alias (backward compatibility)
